protected/controllers/DrugController.php
<?php

class DrugController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'index' 'view' 'create' 'update' 'delete' actions
				'actions'=>array('index','view','create','update','delete','getDoses'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' actions
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model=$this->loadModel($id);
		if(!Helpers::checkAuth($model))
			throw new CHttpException(400,'Invalid request.');
		
		$tapers=new CActiveDataProvider('Taper',array(
			'criteria'=>array(
				'with'=>'drug',
				'condition'=>'drug_id=:id',
				'params'=>array(':id'=>$id),
				'order'=>'active DESC, completed DESC',
			),
		));
		$pills=new CActiveDataProvider('Pill',array(
			'criteria'=>array(
				'condition'=>'drug_id=:id',
				'params'=>array(':id'=>$id),
				'order'=>'name',
			),
		));
		
		$this->render('view',array(
			'model'=>$model,
			'tapers'=>$tapers,
			'pills'=>$pills,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Drug;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Drug'])) {
			$model->attributes=$_POST['Drug'];
			$model->user_id=Yii::app()->user->id;
			if ($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);
		if(!Helpers::checkAuth($model) || !Helpers::checkAdmin())
			throw new CHttpException(400,'Invalid request');
		
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Drug'])) {
			$model->attributes=$_POST['Drug'];
			if ($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		// we only allow deletion via POST request
		if (Yii::app()->request->isPostRequest)
		{
			if (Helpers::checkAuth($model)) 
			{
				$model->delete();

				// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
				if (!isset($_GET['ajax'])) {
					$this->redirect(array('index'));
				} else {
					$this->redirect(array('admin'));
				}
			} else {
				throw new CHttpException(400,'Invalid request');
			}
		} else {
			throw new CHttpException(400,'Invalid request');
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		// Limit results to those belonging to the user unless user is admin
		if(Helpers::checkAdmin())
		{
			$dataProvider=new CActiveDataProvider('Drug');
		} else {
			$dataProvider=new CActiveDataProvider(Drug::model()->userOwns());
		}
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		if(!Helpers::checkAdmin())
			throw new CHttpException(400,'Invalid request');
		$model=new Drug('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['Drug'])) {
			$model->attributes=$_GET['Drug'];
		}

		$this->render('admin',array(
			'model'=>$model,
		));
	}
        
        /**
         * Call by ajax to get dose history for drug
         */
        public function actionGetDoses($id)
        {
            //$drug=$this->loadModel($id);
            $data=array();
            $criteria=new CDbCriteria();
            $criteria->with='pill';
            $criteria->together=true;
            $criteria->condition='pill.drug_id=:id';
            $criteria->params=array(':id'=>$id);
            $criteria->order='date DESC';
            $doses=Dose::model()->findAll($criteria);
            foreach($doses as $dose)
            {
                $data[]=array(
                    'id'=>$dose->id,
                    'dose'=>Pill::getDose($dose->pill_id, $dose->weight),
                    'date'=>date_parse($dose->date),
                );
            }
            $this->renderJSON($data);
        }

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Drug the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Drug::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Drug $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax']==='drug-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/PillController.php
<?php

class PillController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index','view','create','update','delete','getPills','setDefault'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the drug id to associate this pill to
	 */
	public function actionCreate($id)
	{
		$model=new Pill;
		$model->drug_id=$id;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Pill'])) {
			$model->attributes=$_POST['Pill'];
			//$model->drug_id=$id;
			if ($model->save()) {
				$this->redirect(array('drug/view','id'=>$id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Pill'])) {
			$model->attributes=$_POST['Pill'];
			if ($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$model=$this->loadModel($id);
		// we only allow deletion via POST request
		if (Yii::app()->request->isPostRequest)
		{
			if (Helpers::checkAuth($model)) 
			{
				$model->delete();

				// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
				if (!isset($_GET['ajax'])) {
					$this->redirect(array('index'));
				} else {
					$this->redirect(array('admin'));
				}
			} else {
				throw new CHttpException(400,'Invalid request.');
			}
		} else {
			throw new CHttpException(400,'Invalid request.');
		}
	}


	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Pill');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Pill('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['Pill'])) {
			$model->attributes=$_GET['Pill'];
		}

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Pill the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Pill::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Called from dose/create by ajax to retrieve pills for a given drug_id
	 * @throws CHttpException
	 */
	public function actionGetPills()
	{
		if(!Yii::app()->request->isAjaxRequest)
			throw new CHttpException(400,'Invalid request');
		$drug_id=$_POST['Dose']['drug_id'];
		
		$criteria=new CDbCriteria();
		//$criteria->select='id,name';
		
		$criteria->condition='drug_id=:id';
		$criteria->params=array(':id'=>$drug_id);
		
		$pills=Pill::model()->findAll($criteria);
		foreach($pills as $pill)
		{
			echo TbHtml::tag('option', array('value'=>$pill->id,'selected'=>$pill->default), TbHtml::encode($pill->name), true);

		}
	}
	
	/**
	 * Called from drug/view to toggle default status for a given pill
	 * @throws CHttpException
	 */
	public function actionSetDefault()
	{
		if(!Yii::app()->request->isAjaxRequest)
			throw new CHttpException(400,'Invalid request');
		$pill_id=$_POST['id'][0];
		$drug_id=$_POST['drug_id'];
		
		$criteria=new CDbCriteria();
		$criteria->condition='drug_id=:drug_id';
		$criteria->params=array(':drug_id'=>$drug_id);
		
		$pills=Pill::model()->findAll($criteria);
		foreach($pills as $pill)
		{
			if($pill->id===$pill_id)
			{
				$pill->default=true;
				$pill->save(false);
			}
			else
			{
				$pill->default=false;
				$pill->save(false);
			}
		}
		
	}
	
	/**
	 * Performs the AJAX validation.
	 * @param Pill $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax']==='pill-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/controllers/TaperController.php
<?php

class TaperController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform actions
				'actions'=>array('index','view','create','update','delete'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' actions
				'actions'=>array('admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the drug id to add taper to
	 */
	public function actionCreate($id)
	{
		$model=new Taper;
		$model->drug_id=$id;
		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Taper'])) {
			$model->attributes=$_POST['Taper'];
			
			if ($model->save()) {
				$this->redirect(array('drug/view','id'=>$id));
			}
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Taper'])) {
			$model->attributes=$_POST['Taper'];
			if ($model->save()) {
				$this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		if (Yii::app()->request->isPostRequest) {
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if (!isset($_GET['ajax'])) {
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
			}
		} else {
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Taper');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Taper('search');
		$model->unsetAttributes();  // clear any default values
		if (isset($_GET['Taper'])) {
			$model->attributes=$_GET['Taper'];
		}

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Taper the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Taper::model()->findByPk($id);
		if ($model===null) {
			throw new CHttpException(404,'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Taper $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax']==='taper-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/drug/_doseGraph.php
<?php
/* @var $this DrugController */
/* @var $model Drug */
/* @var $tapers CActiveDataProvider */
/* @var $pills CActiveDataProvider */
?>

<?php echo TbHtml::well('', array(
	'id'=>'drug-dose-graph',
	'style'=>'height: 200px;',
)); ?>
<?php $clientScript = Yii::app()->clientScript; ?>
<?php $clientScript->registerScriptFile('http://d3js.org/d3.v3.min.js', JClientScript::POS_END); ?>
<?php $clientScript->registerCssFile(Yii::app()->createAbsoluteUrl('../css/graph.css')); ?>
<?php $clientScript->beginScript('drug-dose-script', JClientScript::POS_END); ?>
<script type="text/javascript">
    var margin = {top: 20, right: 20, bottom: 30, left: 50},
        width = parseInt(d3.select("#drug-dose-graph").style("width")) - margin.left - margin.right,
        height = parseInt(d3.select("#drug-dose-graph").style("height")) - margin.top - margin.bottom;

    var x = d3.time.scale()
        .range([0, width]);

    var y = d3.scale.linear()
        .range([height, 0]);

    var xAxis = d3.svg.axis()
        .scale(x)
        .orient("bottom");

    var yAxis = d3.svg.axis()
        .scale(y)
        .orient("left");
	
	resample;

    var line = d3.svg.line()
        .x(function(d) { return x(d.date); })
        .y(function(d) { return y(d.dose); });

    var svg = d3.select("#drug-dose-graph").append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

    d3.xhr("<?php echo Yii::app()->createUrl('/drug/getDoses', array('id'=>$model->id)); ?>")
        .header("Content-Type", "application/json")
        .post("", function(error, data) {
            data=JSON.parse(data.responseText);

            data.forEach(function(d) {
                    d.date=new Date(d.date.year,d.date.month,d.date.day);
            });

            x.domain(d3.extent(data, function(d) { return d.date; }));
            y.domain(d3.extent(data, function(d) { return d.dose; }));			

            svg.append("g")
                .attr("class", "x axis")
                .attr("transform", "translate(0," + height + ")")
                .call(xAxis);

            svg.append("g")
                .attr("class", "y axis")
                .call(yAxis)
                .append("text")
                    .attr("transform", "rotate(-90)")
                    .attr("y", -40)
                    .attr("dy", ".71em")
                    .style("text-anchor", "end")
                    .text("Dose (mg)");

            svg.append("path")
                .datum(data)
                .attr("class", "line")
                .attr("d", line);
        });
	
		
	function resize() {
		var width = parseInt(d3.select("#drug-dose-graph").style("width")) - margin.left - margin.right,
			height = parseInt(d3.select("#drug-dose-graph").style("height")) - margin.top - margin.bottom;

		x.range([0,width]);
		y.range([height,0]);
		xAxis.ticks(Math.max(width/70, 2));
		yAxis.ticks(Math.max(height/70, 2));
		svg.select(".x.axis")
			.attr("transform", "translate(0," + height + ")")
			.call(xAxis);
		svg.select(".y.axis")
			.call(yAxis);
		svg.select(".line")
			.attr("d", line);
		resample;
		
	}
	
	function resample() {
		dataPerPixel = data.length/width;
		dataResampled = data.filter(
			function(d, i) { return i % Math.ceil(dataPerPixel) == 0; }
		);
	}
	
	d3.select(window).on('resize', resize);
</script>
<?php $clientScript->endScript(); ?>

protected/views/drug/_form.php
<?php
/* @var $this DrugController */
/* @var $model Drug */
/* @var $form TbActiveForm */
?>

<div class="form">

    <?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'drug-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

    <p class="help-block">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

            <?php echo $form->textFieldControlGroup($model,'name',array('span'=>5,'maxlength'=>255)); ?>

            <?php echo $form->textFieldControlGroup($model,'nick',array('span'=>5,'maxlength'=>255)); ?>

            <?php echo $form->textFieldControlGroup($model,'half_life_low',array('span'=>5)); ?>

            <?php echo $form->textFieldControlGroup($model,'half_life_high',array('span'=>5)); ?>

        <div class="form-actions">
        <?php echo TbHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array(
		    'color'=>TbHtml::BUTTON_COLOR_PRIMARY,
		    'size'=>TbHtml::BUTTON_SIZE_LARGE,
		)); ?>
    </div>

    <?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/drug/_view.php
<?php
/* @var $this DrugController */
/* @var $data Drug */
?>

<div class="view">

	<b><?php echo CHtml::link(CHtml::encode($data->name),array('view','id'=>$data->id)); ?></b>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nick')); ?>:</b>
	<?php echo CHtml::encode($data->nick); ?>
	<br />

	<b>Half Life:</b>
	<?php echo CHtml::encode(Helpers::halfLifeRange($data->half_life_low,$data->half_life_high)); ?>
	<br />

	<b>Username:</b>
	<?php echo CHtml::encode($data->user->username); ?>
	<br />


</div>

protected/views/drug/view.php
<?php
/* @var $this DrugController */
/* @var $model Drug */

/* @var $tapers CActiveDataProvider */
/* @var $pills CActiveDataProvider */
?>

<?php
$this->breadcrumbs=array(
	array('label'=>'Drugs','url'=>array('index')),
	array('label'=>$model->name),
);

$this->menu=array(
		array('label'=>'List drugs', 'url'=>array('index')),
		array('label'=>'Add drug', 'url'=>array('create')),
		array('label'=>'Edit drug', 'url'=>array('update', 'id'=>$model->id)),
		array('label'=>'Delete this drug', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>"Are you sure you want to delete this drug?\nAll associated information (tapers, pills, etc) will be removed")),
);
if(Helpers::checkAdmin())
{
	$this->menu[]=array('label'=>'Manage drugs', 'url'=>array('admin'));
}
?>

<h1><?php echo $model->name.' ('.$model->nick.')'; ?></h1>

<?php 
// Show minimal attributes unless admin
if(Helpers::checkAdmin())
{
	$attr=array(
		'id',
		'name',
		'nick',
		'half_life_low',
		'half_life_high',
		'user.username',
		'created',
		'updated',
	);
} else {
	$attr=array(
		
	);
}

$this->widget('zii.widgets.CDetailView',array(
    'htmlOptions' => array(
        'class' => 'table table-striped table-condensed table-hover',
    ),
    'data'=>$model,
    'attributes'=>$attr,
)); ?>

<h2>Doses</h2>

<?php $this->renderPartial('_doseGraph',array(
    'model'=>$model,
    'tapers'=>$tapers,
    'pills'=>$pills,
)); ?>

<?php echo TbHtml::button('Add doses', array(
	'submit'=>array('dose/create','id'=>$model->id),
	'color'=>TbHtml::BUTTON_COLOR_PRIMARY,
	'style'=>'margin-bottom: 5px;',
)); ?>

<h2>Tapers</h2>

<?php echo TbHtml::button('Add taper', array(
	'submit'=>array('taper/create','id'=>$model->id),
	'color'=>TbHtml::BUTTON_COLOR_PRIMARY,
	'style'=>'margin-bottom: 5px;',
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'drug-taper-grid',
	'dataProvider'=>$tapers,
	'columns'=>array(
		'drug.name',
		'start_dose',
		'end_dose',
		'step_size',
		'step_freq',
		'active',
		'completed',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{view} {update} {delete}',
			'buttons'=>array(
				'view'=>array(
					'label'=>'View taper',
					'url'=>'Yii::app()->createUrl("taper/view",array("id"=>$data->id))',
				),
				'update'=>array(
					'label'=>'Edit taper',
					'url'=>'Yii::app()->createUrl("taper/update",array("id"=>$data->id))',
				),
				'delete'=>array(
					'label'=>'Delete taper',
					'url'=>'Yii::app()->createUrl("taper/delete",array("id"=>$data->id))',
				),
			),
		),
	),
)); ?>



<h2>Pills</h2>

<?php echo TbHtml::button('Add pill', array(
	'submit'=>array('pill/create','id'=>$model->id),
	'color'=>TbHtml::BUTTON_COLOR_PRIMARY,
	'style'=>'margin-bottom: 5px;',
)); ?>

<?php $this->widget('bootstrap.widgets.TbGridView',array(
	'id'=>'drug-pill-grid',
	'type'=>'striped',
	'dataProvider'=>$pills,
	'columns'=>array(
		'name',
		'weight',
		'empty_weight',
		'dose',
		array(
			'class'=>'CCheckBoxColumn',
			'header'=>'Default',
			'id'=>'default',
			'selectableRows'=>1,
			'value'=>'$data->default',
			'checked'=>'$data->default==1',
		),
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
			'template'=>'{view} {update} {delete}',
			'buttons'=>array(
				'view'=>array(
					'label'=>'View pill',
					'url'=>'Yii::app()->createUrl("pill/view",array("id"=>$data->id))',
				),
				'update'=>array(
					'label'=>'Edit pill',
					'url'=>'Yii::app()->createUrl("pill/update",array("id"=>$data->id))',
				),
				'delete'=>array(
					'label'=>'Delete pill',
					'url'=>'Yii::app()->createUrl("pill/delete",array("id"=>$data->id))',
				),
			),
		),
	),
)); ?>

<?php 
$url=Yii::app()->createUrl('pill/setDefault');
$cs = Yii::app()->clientScript->registerScript(
  'update-default-pill-on-check',
  "$('#drug-pill-grid :checkbox').change(function() {
	  $.ajax({
		type: 'POST',
		url: \"{$url}\",
		data: {
			id: $('#drug-pill-grid').yiiGridView('getChecked', 'default'),
			drug_id: \"{$model->id}\"
		}
	  });
	});"
);
?>